###POST
POST http://localhost:3000/api/usuarios HTTP/1.1
Content-Type: application/json

{
  "oficina": "Movilnet",
  "correo": "prueba@movilnet.com.ve",
  "estado": "Bloqueado",
  "nombre": "Pruebase",
  "apellido": "System",
  "cedula": "00000000",
  "password": "12345678",
  "roles": ["6949b74d15750b560f9dc29f"]
}

###GET
GET http://localhost:3000/api/usuarios HTTP/1.1

###PUT
PUT http://localhost:3000/api/usuarios/6961ab30e38d4ac9327946b5 HTTP/1.1
Content-Type: application/json

{
  "oficina": "Movilnet",
  "correo": "fae@movilnet.com",
  "estado": "Activo",
  "nombre": "aefas",
  "apellido": "asfea",
  "cedula": "434352",
  "password": "2522525",
  "roles": ["6949b74d15750b560f9dc29e"]
}

###SHOW
GET http://localhost:3000/api/usuarios/6961af18a3804e923eba539f HTTP/1.1

###DELETE
DELETE http://localhost:3000/api/usuarios/693143e84a22b5c3b19b213d HTTP/1.1
Content-Type: application/json

### Crear un nuevo rol
POST http://localhost:3000/api/roles HTTP/1.1
Content-Type: application/json

{
  "nombre": "Supervisor",
  "descripcion": "Rol de supervisión con permisos intermedios",
  "permisos": ["leer", "consultar", "asignar", "reasignar"]
}

### Obtener todos los roles
GET http://localhost:3000/api/roles HTTP/1.1

### Obtener un rol por ID (Administrador)
GET http://localhost:3000/api/roles/6931cbef8a1692ac419dc2a9 HTTP/1.1

### Actualizar un rol (Agente)
PUT http://localhost:3000/api/roles/6931cbef8a1692ac419dc2aa HTTP/1.1
Content-Type: application/json

{
  "nombre": "Agente",
  "descripcion": "Agente con permisos extendidos",
  "permisos": ["consultar", "asignar", "reasignar", "leer"]
}

### Eliminar un rol (Moderado)
DELETE http://localhost:3000/api/roles/6931cbef8a1692ac419dc2ab HTTP/1.1
Content-Type: application/json

###POST numeros
POST http://localhost:3000/api/numeros HTTP/1.1
Content-Type: application/json

{
  "cedula": "V-54482125",
  "estatus": "Disponible",
  "numeroTelefono": "04141234567",
  "fecha_creacion": "2025-12-04",
  "fecha_actualizacion": "2025-12-04"
}


###GET numeros
GET http://localhost:3000/api/numeros HTTP/1.1

###PUT numeros
PUT http://localhost:3000/api/numeros/6934dd3f71b2488d431cd2d9 HTTP/1.1
Content-Type: application/json

{
  "cedula": "V-99999999",
  "estatus": "Ocupado",
  "numeroTelefono": "04147777777",
  "fecha_creacion": "2025-12-06",
  "fecha_actualizacion": "2025-12-06"
}

###SHOW numeros
GET http://localhost:3000/api/numeros/6934dd3f71b2488d431cd2d9 HTTP/1.1


###POST suscriptor
POST http://localhost:3000/api/suscriptor HTTP/1.1
Content-Type: application/json

{
  "numeroTelefono": "04265848844",
  "estatus": "Activo",
  "operador": "Agente222",
  "fecha": "2025-12-04T02:56:26.000Z",
  "whatsapp": true,
  "telegram": false,
  "cedula": "V-253451"
}

###GET suscriptor
GET http://localhost:3000/api/suscriptor HTTP/1.1

###PUT suscriptor
PUT http://localhost:3000/api/suscriptor/6934dd4071b2488d431cd2db HTTP/1.1
Content-Type: application/json

{
  "numeroTelefono": "04265848844",
  "estatus": "Activo",
  "operador": "Agente222",
  "fecha": "2025-12-04T02:56:26.000Z",
  "whatsapp": true,
  "telegram": false,
  "cedula": "V-253451"
}

###SHOW suscriptor
GET http://localhost:3000/api/suscriptor/6934dd4071b2488d431cd2db HTTP/1.1

### Login
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json

{
  "Usuario": "admin@movilnet.com.ve",
  "Password": "12345678"
}
### Logout
POST http://localhost:3000/api/logout HTTP/1.1
Content-Type: application/json

### Update Password (Requires Auth Token)
POST http://localhost:3000/api/update-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MzRlODRlYjUzMGIwZjhiYTczZWY5OCIsImNvcnJlbyI6Imx1aXNAbW92aWxuZXQuY29tIiwicm9sZXMiOltdLCJpYXQiOjE3NjY0MTg4NTMsImV4cCI6MTc2NjQyMjQ1M30.ZDG6ZRHhYK_xWnYIIx47eC3Zc17EtPyWZ1aAUieQFY

{
  "currentPassword": "12345678",
  "newPassword": "12345678"
}

### Profile (Requires Auth Token)
GET http://localhost:3000/api/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NDliNzliN2EwM2VkODRiYmRjZTA2YiIsImNvcnJlbyI6ImFkbWluQG1vdmlsbmV0LmNvbS52ZSIsInJvbGVzIjpbeyJfaWQiOiI2OTQ5Yjc0ZDE1NzUwYjU2MGY5ZGMyOWQiLCJub21icmUiOiJBZG1pbmlzdHJhZG9yIiwiZGVzY3JpcGNpb24iOiJBZG1pbmlzdHJhZG9yIGRlbCBzaXN0ZW1hLiIsInBlcm1pc29zIjpbImNyZWFyIiwibGVlciIsImJsb3F1ZWFyIiwiYWN0dWFsaXphciIsImNvbnN1bHRhciJdfV0sImlhdCI6MTc2ODA3Njk3NiwiZXhwIjoxNzY4MDgwNTc2fQ.LYNs9s-rRqFFCl-czsQHKtKLJDhH9zMfnJ2qeGMMRaQ
